### ISSUE TITLE
Unsupported operand types: string / int (in class-fire-resources_fonts.php:190)

### ISSUE THREAD

**Issue by ghost** [Nikeo/customizr#1892]
Hello there,

While doing some experiments with the Font Customizr, I noticed that when the font size is left blank, instead of the expected behaviour - no font size overriding - the size is specifically set to zero, thus turning text invisible.

Why did I want to leave the font size untouched? Well, essentially because your own defaults work great - I often just want to change font type and colour, but rarely size. The trouble is that any value set for the font size - even 'blank' will throw the following error under PHP 8.0.3:

```
2021/03/17 21:46:01 [error] 353227#353227: *499380 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught TypeError: Unsupported operand types: string / int in /var/www/clients/client6/web11/web/wp-content/themes/customizr-pro/core/class-fire-resources_fonts.php:190
Stack trace:
#0 /var/www/clients/client6/web11/web/wp-includes/class-wp-hook.php(292): CZR_resources_fonts->czr_fn_write_fonts_inline_css()
#1 /var/www/clients/client6/web11/web/wp-includes/plugin.php(212): WP_Hook->apply_filters()
#2 /var/www/clients/client6/web11/web/wp-content/themes/customizr-pro/core/class-fire-resources_styles.php(75): apply_filters()
#3 /var/www/clients/client6/web11/web/wp-includes/class-wp-hook.php(292): CZR_resources_styles->czr_fn_enqueue_front_styles()
#4 /var/www/clients/client6/web11/web/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#5 /var/www/clients/client6/web11/web/wp-includes/plugin.php(484): WP_Hook->do_action()
#6 /var/www/clients/client6/web11/web/wp-includes/script-loader.php(2027): do_action()
#7 /var/www/clients/client6/web11/web/wp-includes/c" while reading response header from upstream, client: 2001:8a0:710e:fa00:3972:2585:42ba:a0b7, server: betatechnologies.info, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php7.3-fpm/web11.sock:", host: "betatechnologies.info", referrer: "https://betatechnologies.info/blog/museum-exhibit-inside-lisbon-1755-project-on-kitely"
```

I believe that this has mostly to do with PHP 8's much stricter type-checking (note: although the above log shows a socket named php7.3, it is running 8.0.3 - it's just that my configuration is quite weird and hasn't been 'cleaned up' yet). In the relevant code - $remsize = $_body_font_size / 16; - what happens is that $_body_font_size may be a string (which is certainly true in the case of a blank setting!) and not an integer. PHP 7 would throw a warning, but nevertheless attempt to convert the string to a numeric value; PHP 8 gives a fatal error instead.

One attempt to 'fix' this issue is shown on the following code (it's backwards-compatible with PHP 7):

```
if ( empty( $_body_font_size ) || ! is_numeric( $_body_font_size ) ) $_body_font_size = 15;
if ( 15 != $_body_font_size && is_null( $_context ) ) {
$_line_height = apply_filters('czr_body_line_height_ratio', 1.5 );
if ( !czr_fn_is_checked( 'tc_ms_respond_css' ) ) {
//turn into rem
$remsize = (int)$_body_font_size / 16;
$remsize = number_format( (float)$remsize, 2, '.', '');
$_css .= "
{$body} {
font-size : {$remsize}rem;
line-height : {$_line_height}em;
}n";
} else {
// June 2019 => increase the ratio from 0.833 to 0.9 to limit problems when deactivating
// @see https://github.com/presscustomizr/customizr/issues/1755
$emsize_medium = (int)$_body_font_size * 0.900 / 16;//@see assets/css/front/stye-modular-
$emsize_medium = number_format( (float)$emsize_medium, 2, '.', '');
$emsize_large = (int)$_body_font_size * 0.9375 / 16;
$emsize_large = number_format( (float)$emsize_large, 2, '.', '');
```

The idea here is to check if $_body_font_size has some sort of valid numerical value (and force it to 15 otherwise), as well as explicitly casting it to an integer. Note that the first line of code may be enough to force $_body_font_size to be an integer and not a string, thus making the explicit typecasts unnecessary. I haven't tested that.

Anyway, in any case, I understand that your worries about converting whatever the user types in Font Customizr to something (r)em-based may not be so relevant any more, and all your code - which assumes that the 'default' font size set in all browsers is 16pt - may have to be changed to reflect the ever-evolving CSS usage guidelines...

The main reason for reporting this bug (assuming it is a bug!) is that I expect to continue to use PHP 8 when your next version of Customizr Pro comes out, and I'll have to make whatever changes I did again, for each successive version. With luck, I just need to add one line of code... but I can't forget to do that for every release! Or else I'll get a website with most fonts with a zero size, and people will complain...

I'm looking forward to your 'fix'!

Thank you in advance.

https://secure.helpscout.net/conversation/1459775425/225287/

**Comment by ghost** [comment]
Thanks for reporting the problem.
Working on a fix.
